language: python

python:
  - "3.6"

cache: pip

before_install: cd backend

install:
  - pip install --upgrade pip setuptools
  - pip install -r requirements.txt

script:
  - python tests/tests_viperid.py